import sys
import requests
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(838, 350)
        self.Hujan = QtWidgets.QLabel(Dialog)
        self.Hujan.setGeometry(QtCore.QRect(20, 80, 121, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Hujan.setFont(font)
        self.Hujan.setObjectName("Hujan")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(290, 80, 121, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lcdHujan = QtWidgets.QLCDNumber(Dialog)
        self.lcdHujan.setGeometry(QtCore.QRect(60, 80, 64, 23))
        self.lcdHujan.setObjectName("lcdHujan")
        self.lcdKelembapan_2 = QtWidgets.QLCDNumber(Dialog)
        self.lcdKelembapan_2.setGeometry(QtCore.QRect(370, 80, 64, 23))
        self.lcdKelembapan_2.setObjectName("lcdKelembapan_2")
        self.graphicsHujan = QtWidgets.QGraphicsView(Dialog)
        self.graphicsHujan.setGeometry(QtCore.QRect(20, 110, 256, 192))
        self.graphicsHujan.setObjectName("graphicsHujan")
        self.graphicsKelembapan = QtWidgets.QGraphicsView(Dialog)
        self.graphicsKelembapan.setGeometry(QtCore.QRect(290, 110, 256, 192))
        self.graphicsKelembapan.setObjectName("graphicsKelembapan")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(340, 10, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.timeEdit = QtWidgets.QTimeEdit(Dialog)
        self.timeEdit.setGeometry(QtCore.QRect(700, 310, 118, 22))
        self.timeEdit.setObjectName("timeEdit")
        self.lcdSuhu = QtWidgets.QLCDNumber(Dialog)
        self.lcdSuhu.setGeometry(QtCore.QRect(600, 80, 64, 23))
        self.lcdSuhu.setObjectName("lcdSuhu")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(560, 80, 41, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.graphicsSuhu = QtWidgets.QGraphicsView(Dialog)
        self.graphicsSuhu.setGeometry(QtCore.QRect(560, 110, 256, 192))
        self.graphicsSuhu.setObjectName("graphicsSuhu")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(670, 80, 41, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(440, 80, 21, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(0, 50, 851, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        # Set timer to update data
        self.timer = QtCore.QTimer()
        self.timer.timeout.connect(self.update_data)
        self.timer.start(2000)  # Update every 2 seconds

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.Hujan.setText(_translate("Dialog", "Rain :"))
        self.label_2.setText(_translate("Dialog", "Kelembapan :"))
        self.label_6.setText(_translate("Dialog", "Mini Stasiun Cuaca"))
        self.label_3.setText(_translate("Dialog", "Suhu :"))
        self.label_4.setText(_translate("Dialog", "⁰C"))
        self.label_5.setText(_translate("Dialog", "%"))

    def update_data(self):
        try:
            # Replace <ESP32_IP_ADDRESS> with the actual IP address of your ESP32
            response = requests.get('http://<192.168.167.30>/')
            data = response.text.split('\n')
            humidity = float(data[0].split(': ')[1])
            temperature = float(data[1].split(': ')[1])
            rain_intensity = int(data[2].split(': ')[1])

            self.lcdKelembapan_2.display(humidity)
            self.lcdSuhu.display(temperature)
            self.lcdHujan.display(rain_intensity)
        except Exception as e:
            print(f"Error: {e}")

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
